name: feature

on:
  push:
    branches-ignore:
      - 'master'
      - 'develop'

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle # the build with gradlew step runs gradlew wrapper script to ensure that your code builds. test pass, and a package can be created.
        run: ./gradlew build

# d6394b4ed1b24c870d5d4d1a74128acd940fcfb2